#!/bin/bash

line=$2

[ "$line" = "usage" ] && {
	echo "  Follow up on item:"
	echo "    followup [ID] [date]"
	echo "   default date is next week"
	echo ""
	exit
}
[ "$line" = "ls" ] && {
	"$TODO_SH" -x command ls "@followup:"
	exit
}

if [ $#	= 3 ]
then
	date=$(date --iso-8601 --date="$(echo $3)")
else
	date=$(date --iso-8601 --date="next week")
fi
echo $date

# we get the text of the item
tofollowup=$(head -n "$line" "$TODO_FILE" | tail -n 1)
# we remove the priority
tofollowup=$(sed 's/^([A-Z]) //' <(echo $tofollowup))
# we remove the creation date
tofollowup=$(sed 's/[0-9,-]\+ //' <(echo $tofollowup))
# we remove the start date because we are adding a new one
# TODO test this
tofollowup=$(sed 's/t:[0-9,-]\+//' <(echo $tofollowup))
# TODO do not add another @followup: if it is already there, just change the date
# we DO the item
"$TODO_SH" command do "$line"
# add new follow up item
"$TODO_SH" command add "@followup: $tofollowup t:$date"
